### ISSUE TITLE
Does JAML support <i> tags? Is there an easy way to add that?

### ISSUE THREAD

**Issue by bjmc** [edspencer/jaml#22]
I know `<i>` tags are semi-deprecated in favor of `<em>`, but it's mildly disappointing that there's no easy way to generate a standard HTML tag that's been around since HTML 2.0.

Any suggestions? Can I define custom tags?

**Comment by edspencer** [comment]
I've added &lt;i&gt; and &lt;b&gt; tags to the file. Hadn't touched this in years so I hope it works :)

**Comment by bjmc** [comment]
Thanks!
